const mongoose = require('mongoose');

const repaymentModeSchema = new mongoose.Schema({
  name: { type: String, required: true }, // Monthly, Quarterly, Half-Yearly, Annual
  numberOfInstallments: { type: Number, required: true },
  description: { type: String },
  dueDayOfMonth: { type: Number }, // e.g. 10 => 10th of every month
  customDueDates: [Date], // for fixed due dates
  autoGenerateDueDates: { type: Boolean, default: true },
  organisationId: { type: mongoose.Schema.Types.ObjectId, ref: 'Organisation', required: true },
  isActive: { type: Boolean, default: true },
}, { timestamps: true });

module.exports = mongoose.model('RepaymentMode', repaymentModeSchema);
